/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Stock } from './types.ts';

export const INITIAL_BALANCES: Record<string, number> = {
  '$': 1000000,
  '₹': 1000000
};

export const MOCK_STOCKS: Stock[] = [
  {
    "symbol": "AAPL",
    "name": "Apple Inc.",
    "price": 336.13,
    "change": -0.87,
    "changePercent": -0.26,
    "volume": "86.2M",
    "marketCap": "4.91T",
    "description": "Tech leader.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 338.49,
    "dayLow": 332.53,
    "prevClose": 337
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft Corp.",
    "price": 493.78,
    "change": -3.97,
    "changePercent": -0.8,
    "volume": "39.4M",
    "marketCap": "3.67T",
    "description": "Software giant.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 498.65,
    "dayLow": 491.1,
    "prevClose": 497.75
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA Corp.",
    "price": 222.27,
    "change": 2.93,
    "changePercent": 1.34,
    "volume": "188.8M",
    "marketCap": "5.37T",
    "description": "AI compute hardware.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 222.73,
    "dayLow": 218.04,
    "prevClose": 219.34
  },
  {
    "symbol": "GOOGL",
    "name": "Alphabet Inc.",
    "price": 349.54,
    "change": 2.21,
    "changePercent": 0.64,
    "volume": "47.5M",
    "marketCap": "4.27T",
    "description": "Search & Cloud.",
    "sector": "Communication Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 359.44,
    "dayLow": 348.45,
    "prevClose": 347.33
  },
  {
    "symbol": "AMZN",
    "name": "Amazon.com Inc.",
    "price": 253.71,
    "change": 2.52,
    "changePercent": 1,
    "volume": "52.0M",
    "marketCap": "2.74T",
    "description": "E-commerce & Cloud.",
    "sector": "Consumer Cyclical",
    "country": "USA",
    "currency": "$",
    "dayHigh": 255.43,
    "dayLow": 251.88,
    "prevClose": 251.19
  },
  {
    "symbol": "META",
    "name": "Meta Platforms",
    "price": 665.75,
    "change": -16.56,
    "changePercent": -2.43,
    "volume": "27.4M",
    "marketCap": "1.70T",
    "description": "Social Media & AI.",
    "sector": "Communication Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 690.15,
    "dayLow": 660.8,
    "prevClose": 682.31
  },
  {
    "symbol": "TSLA",
    "name": "Tesla Inc.",
    "price": 364.27,
    "change": -1.93,
    "changePercent": -0.53,
    "volume": "51.8M",
    "marketCap": "1.44T",
    "description": "EV & Robotics pioneer.",
    "sector": "Consumer Cyclical",
    "country": "USA",
    "currency": "$",
    "dayHigh": 370.9,
    "dayLow": 360.75,
    "prevClose": 366.2
  },
  {
    "symbol": "AVGO",
    "name": "Broadcom Inc.",
    "price": 357.61,
    "change": 10.31,
    "changePercent": 2.97,
    "volume": "43.9M",
    "marketCap": "1.71T",
    "description": "Semiconductors & Infrastructure.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 363.28,
    "dayLow": 351.35,
    "prevClose": 347.3
  },
  {
    "symbol": "COST",
    "name": "Costco Wholesale",
    "price": 895.31,
    "change": 1.38,
    "changePercent": 0.15,
    "volume": "4.2M",
    "marketCap": "397.1B",
    "description": "Membership retail leader.",
    "sector": "Consumer Defensive",
    "country": "USA",
    "currency": "$",
    "dayHigh": 898.4,
    "dayLow": 890.96,
    "prevClose": 893.93
  },
  {
    "symbol": "PEP",
    "name": "PepsiCo Inc.",
    "price": 129.75,
    "change": -3.91,
    "changePercent": -2.93,
    "volume": "23.4M",
    "marketCap": "177.2B",
    "description": "Beverages & Snacks.",
    "sector": "Consumer Defensive",
    "country": "USA",
    "currency": "$",
    "dayHigh": 132.26,
    "dayLow": 129.55,
    "prevClose": 133.66
  },
  {
    "symbol": "NFLX",
    "name": "Netflix Inc.",
    "price": 71.79,
    "change": -3.52,
    "changePercent": -4.67,
    "volume": "113.6M",
    "marketCap": "298.9B",
    "description": "Streaming entertainment.",
    "sector": "Communication Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 72.38,
    "dayLow": 70.11,
    "prevClose": 75.31
  },
  {
    "symbol": "ADBE",
    "name": "Adobe Inc.",
    "price": 248.92,
    "change": -3.75,
    "changePercent": -1.48,
    "volume": "10.2M",
    "marketCap": "98.9B",
    "description": "Creative software & cloud.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 252.67,
    "dayLow": 247.21,
    "prevClose": 252.67
  },
  {
    "symbol": "CSCO",
    "name": "Cisco Systems",
    "price": 109.51,
    "change": -0.73,
    "changePercent": -0.66,
    "volume": "41.2M",
    "marketCap": "431.8B",
    "description": "Networking & cybersecurity.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 110.81,
    "dayLow": 108.09,
    "prevClose": 110.24
  },
  {
    "symbol": "INTC",
    "name": "Intel Corp.",
    "price": 108.6,
    "change": -0.2,
    "changePercent": -0.18,
    "volume": "174.4M",
    "marketCap": "574.1B",
    "description": "Semiconductors.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 110.49,
    "dayLow": 106.4,
    "prevClose": 108.8
  },
  {
    "symbol": "AMD",
    "name": "Advanced Micro Devices",
    "price": 559.82,
    "change": 14.73,
    "changePercent": 2.7,
    "volume": "31.7M",
    "marketCap": "913.9B",
    "description": "Semiconductors & AI chips.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 559.91,
    "dayLow": 541.54,
    "prevClose": 545.09
  },
  {
    "symbol": "QCOM",
    "name": "Qualcomm Inc.",
    "price": 177.72,
    "change": -10.99,
    "changePercent": -5.82,
    "volume": "54.4M",
    "marketCap": "189.8B",
    "description": "Wireless technology & chips.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 192.12,
    "dayLow": 175.97,
    "prevClose": 188.71
  },
  {
    "symbol": "TXN",
    "name": "Texas Instruments",
    "price": 266.64,
    "change": 8.5,
    "changePercent": 3.29,
    "volume": "18.8M",
    "marketCap": "243.5B",
    "description": "Analog semiconductors.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 268.26,
    "dayLow": 259.83,
    "prevClose": 258.14
  },
  {
    "symbol": "AMAT",
    "name": "Applied Materials",
    "price": 444.57,
    "change": 27.17,
    "changePercent": 6.51,
    "volume": "14.2M",
    "marketCap": "352.8B",
    "description": "Semiconductor manufacturing equipment.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 445,
    "dayLow": 420,
    "prevClose": 417.4
  },
  {
    "symbol": "ISRG",
    "name": "Intuitive Surgical",
    "price": 393.33,
    "change": 9.79,
    "changePercent": 2.55,
    "volume": "4.9M",
    "marketCap": "140.9B",
    "description": "Robotic surgical systems.",
    "sector": "Healthcare",
    "country": "USA",
    "currency": "$",
    "dayHigh": 394.59,
    "dayLow": 379.5,
    "prevClose": 383.54
  },
  {
    "symbol": "HON",
    "name": "Honeywell Intl",
    "price": 206.46,
    "change": -0.03,
    "changePercent": -0.01,
    "volume": "7.0M",
    "marketCap": "65.4B",
    "description": "Industrial conglomerate.",
    "sector": "Industrials",
    "country": "USA",
    "currency": "$",
    "dayHigh": 207.48,
    "dayLow": 204.26,
    "prevClose": 206.49
  },
  {
    "symbol": "V",
    "name": "Visa Inc.",
    "price": 368.29,
    "change": -1.64,
    "changePercent": -0.44,
    "volume": "19.6M",
    "marketCap": "691.4B",
    "description": "Global payments network.",
    "sector": "Financial Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 370.76,
    "dayLow": 366.93,
    "prevClose": 369.93
  },
  {
    "symbol": "MA",
    "name": "Mastercard Inc.",
    "price": 565.24,
    "change": -0.49,
    "changePercent": -0.09,
    "volume": "5.4M",
    "marketCap": "495.2B",
    "description": "Global payments network.",
    "sector": "Financial Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 568.43,
    "dayLow": 561.9,
    "prevClose": 565.73
  },
  {
    "symbol": "JPM",
    "name": "JPMorgan Chase",
    "price": 349.67,
    "change": 0.36,
    "changePercent": 0.1,
    "volume": "18.2M",
    "marketCap": "929.5B",
    "description": "Global banking major.",
    "sector": "Financial Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 349.67,
    "dayLow": 345.07,
    "prevClose": 349.31
  },
  {
    "symbol": "UNH",
    "name": "UnitedHealth Group",
    "price": 376.9,
    "change": 1.69,
    "changePercent": 0.45,
    "volume": "8.6M",
    "marketCap": "338.3B",
    "description": "Healthcare & insurance leader.",
    "sector": "Healthcare",
    "country": "USA",
    "currency": "$",
    "dayHigh": 378.49,
    "dayLow": 372.42,
    "prevClose": 375.21
  },
  {
    "symbol": "DIS",
    "name": "Walt Disney Co.",
    "price": 102.67,
    "change": -2.68,
    "changePercent": -2.54,
    "volume": "19.1M",
    "marketCap": "177.3B",
    "description": "Global entertainment & media.",
    "sector": "Communication Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 105,
    "dayLow": 102.37,
    "prevClose": 105.35
  },
  {
    "symbol": "ORCL",
    "name": "Oracle Corp.",
    "price": 147.61,
    "change": -2.98,
    "changePercent": -1.98,
    "volume": "39.1M",
    "marketCap": "446.3B",
    "description": "Enterprise cloud & database.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 150.9,
    "dayLow": 144.4,
    "prevClose": 150.59
  },
  {
    "symbol": "CRM",
    "name": "Salesforce Inc.",
    "price": 237.92,
    "change": -4.93,
    "changePercent": -2.03,
    "volume": "21.5M",
    "marketCap": "195.8B",
    "description": "Customer relationship cloud.",
    "sector": "Technology",
    "country": "USA",
    "currency": "$",
    "dayHigh": 244.25,
    "dayLow": 236.54,
    "prevClose": 242.85
  },
  {
    "symbol": "NKE",
    "name": "Nike Inc.",
    "price": 35.51,
    "change": -0.85,
    "changePercent": -2.34,
    "volume": "51.5M",
    "marketCap": "52.7B",
    "description": "Athletic footwear & apparel.",
    "sector": "Consumer Cyclical",
    "country": "USA",
    "currency": "$",
    "dayHigh": 36.68,
    "dayLow": 35.5,
    "prevClose": 36.36
  },
  {
    "symbol": "PYPL",
    "name": "PayPal Holdings",
    "price": 52.41,
    "change": -0.53,
    "changePercent": -1,
    "volume": "28.9M",
    "marketCap": "44.8B",
    "description": "Digital payments platform.",
    "sector": "Financial Services",
    "country": "USA",
    "currency": "$",
    "dayHigh": 52.87,
    "dayLow": 52.25,
    "prevClose": 52.94
  },
  {
    "symbol": "SBUX",
    "name": "Starbucks Corp.",
    "price": 95.83,
    "change": -0.84,
    "changePercent": -0.87,
    "volume": "13.1M",
    "marketCap": "109.2B",
    "description": "Premier specialty coffee chain.",
    "sector": "Consumer Cyclical",
    "country": "USA",
    "currency": "$",
    "dayHigh": 96.56,
    "dayLow": 95.11,
    "prevClose": 96.67
  },
  {
    "symbol": "XOM",
    "name": "Exxon Mobil Corp.",
    "price": 163.54,
    "change": 0.27,
    "changePercent": 0.17,
    "volume": "37.6M",
    "marketCap": "672.5B",
    "description": "Oil & gas integrated giant.",
    "sector": "Energy",
    "country": "USA",
    "currency": "$",
    "dayHigh": 163.54,
    "dayLow": 161.31,
    "prevClose": 163.27
  },
  {
    "symbol": "CVX",
    "name": "Chevron Corp.",
    "price": 209.51,
    "change": -2.06,
    "changePercent": -0.97,
    "volume": "47.2M",
    "marketCap": "411.0B",
    "description": "Energy & petrochemical major.",
    "sector": "Energy",
    "country": "USA",
    "currency": "$",
    "dayHigh": 211.9,
    "dayLow": 207.41,
    "prevClose": 211.57
  },
  {
    "symbol": "COP",
    "name": "ConocoPhillips",
    "price": 131.83,
    "change": -1.36,
    "changePercent": -1.02,
    "volume": "18.4M",
    "marketCap": "158.4B",
    "description": "Hydrocarbon exploration & production.",
    "sector": "Energy",
    "country": "USA",
    "currency": "$",
    "dayHigh": 133.33,
    "dayLow": 131.48,
    "prevClose": 133.19
  },
  {
    "symbol": "SPY",
    "name": "SPDR S&P 500 ETF Trust",
    "price": 761.69,
    "change": 0.98,
    "changePercent": 0.13,
    "volume": "65.0M",
    "marketCap": "N/A",
    "description": "S&P 500 Index ETF.",
    "sector": "ETF",
    "country": "USA",
    "currency": "$",
    "dayHigh": 762,
    "dayLow": 757.97,
    "prevClose": 760.71
  },
  {
    "symbol": "GOLD",
    "name": "Gold Spot",
    "price": 4424.9,
    "change": 25.2,
    "changePercent": 0.57,
    "volume": "138.9K",
    "marketCap": "N/A",
    "description": "Safe haven precious metal.",
    "sector": "Commodities",
    "country": "Global",
    "currency": "$",
    "dayHigh": 4439.8,
    "dayLow": 4372.2,
    "prevClose": 4399.7
  },
  {
    "symbol": "SILVER",
    "name": "Silver Spot",
    "price": 67.15,
    "change": 1.05,
    "changePercent": 1.59,
    "volume": "43.2K",
    "marketCap": "N/A",
    "description": "Industrial precious metal.",
    "sector": "Commodities",
    "country": "Global",
    "currency": "$",
    "dayHigh": 67.89,
    "dayLow": 65.74,
    "prevClose": 66.09
  },
  {
    "symbol": "RELIANCE",
    "name": "Reliance Industries",
    "price": 1226.4,
    "change": -17.5,
    "changePercent": -1.41,
    "volume": "15.1M",
    "marketCap": "16.6T",
    "description": "Energy, Retail & Digital Services.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1247.3,
    "dayLow": 1226.4,
    "prevClose": 1243.9
  },
  {
    "symbol": "TCS",
    "name": "Tata Consultancy Services",
    "price": 2105,
    "change": -85,
    "changePercent": -3.88,
    "volume": "6.9M",
    "marketCap": "7.6T",
    "description": "Global IT consulting leader.",
    "sector": "Technology",
    "country": "India",
    "currency": "₹",
    "dayHigh": 2177.3,
    "dayLow": 2101.2,
    "prevClose": 2190
  },
  {
    "symbol": "HDFCBANK",
    "name": "HDFC Bank Ltd.",
    "price": 731,
    "change": 18,
    "changePercent": 2.52,
    "volume": "39.4M",
    "marketCap": "11.3T",
    "description": "Private sector banking benchmark.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 733.8,
    "dayLow": 715.25,
    "prevClose": 713
  },
  {
    "symbol": "INFY",
    "name": "Infosys Ltd.",
    "price": 1051.4,
    "change": -7.2,
    "changePercent": -0.68,
    "volume": "22.1M",
    "marketCap": "4.3T",
    "description": "Next-gen digital services.",
    "sector": "Technology",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1061.9,
    "dayLow": 1038,
    "prevClose": 1058.6
  },
  {
    "symbol": "ICICIBANK",
    "name": "ICICI Bank Ltd.",
    "price": 1338.9,
    "change": -8.7,
    "changePercent": -0.65,
    "volume": "7.5M",
    "marketCap": "9.6T",
    "description": "Full-service commercial banking.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1359.8,
    "dayLow": 1338.9,
    "prevClose": 1347.6
  },
  {
    "symbol": "HINDUNILVR",
    "name": "Hindustan Unilever",
    "price": 1932,
    "change": -10.2,
    "changePercent": -0.53,
    "volume": "2.0M",
    "marketCap": "4.5T",
    "description": "Consumer packaged goods leader.",
    "sector": "Consumer Defensive",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1959.6,
    "dayLow": 1932,
    "prevClose": 1942.2
  },
  {
    "symbol": "SBIN",
    "name": "State Bank of India",
    "price": 996.2,
    "change": 7.5,
    "changePercent": 0.76,
    "volume": "5.7M",
    "marketCap": "9.2T",
    "description": "Premier public sector bank.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 996.2,
    "dayLow": 985.1,
    "prevClose": 988.7
  },
  {
    "symbol": "BHARTIARTL",
    "name": "Bharti Airtel Ltd.",
    "price": 1893.3,
    "change": 57.3,
    "changePercent": 3.12,
    "volume": "14.2M",
    "marketCap": "11.8T",
    "description": "Global telecommunications provider.",
    "sector": "Communication Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1893.3,
    "dayLow": 1835.3,
    "prevClose": 1836
  },
  {
    "symbol": "LICI",
    "name": "LIC of India",
    "price": 407.7,
    "change": 7.7,
    "changePercent": 1.93,
    "volume": "6.9M",
    "marketCap": "5.2T",
    "description": "Life insurance corporation.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 407.7,
    "dayLow": 398.8,
    "prevClose": 400
  },
  {
    "symbol": "ITC",
    "name": "ITC Ltd.",
    "price": 262.3,
    "change": -3.9,
    "changePercent": -1.47,
    "volume": "14.4M",
    "marketCap": "3.3T",
    "description": "Diversified consumer conglomerate.",
    "sector": "Consumer Defensive",
    "country": "India",
    "currency": "₹",
    "dayHigh": 266.6,
    "dayLow": 262.3,
    "prevClose": 266.2
  },
  {
    "symbol": "LT",
    "name": "Larsen & Toubro Ltd.",
    "price": 3885,
    "change": 48.8,
    "changePercent": 1.27,
    "volume": "1.5M",
    "marketCap": "5.3T",
    "description": "EPC projects & heavy manufacturing.",
    "sector": "Industrials",
    "country": "India",
    "currency": "₹",
    "dayHigh": 3898,
    "dayLow": 3846,
    "prevClose": 3836.2
  },
  {
    "symbol": "KOTAKBANK",
    "name": "Kotak Mahindra Bank",
    "price": 412.5,
    "change": -4,
    "changePercent": -0.96,
    "volume": "15.5M",
    "marketCap": "4.1T",
    "description": "Private banking and wealth management.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 419.2,
    "dayLow": 412.5,
    "prevClose": 416.5
  },
  {
    "symbol": "AXISBANK",
    "name": "Axis Bank Ltd.",
    "price": 1257,
    "change": 17,
    "changePercent": 1.37,
    "volume": "5.7M",
    "marketCap": "3.9T",
    "description": "Retail and institutional banking.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1257,
    "dayLow": 1240.5,
    "prevClose": 1240
  },
  {
    "symbol": "ASIANPAINT",
    "name": "Asian Paints Ltd.",
    "price": 2451.3,
    "change": -2.7,
    "changePercent": -0.11,
    "volume": "1.0M",
    "marketCap": "2.3T",
    "description": "Decorative & industrial paints.",
    "sector": "Consumer Defensive",
    "country": "India",
    "currency": "₹",
    "dayHigh": 2474,
    "dayLow": 2438,
    "prevClose": 2454
  },
  {
    "symbol": "TITAN",
    "name": "Titan Company Ltd.",
    "price": 4798.5,
    "change": -42.5,
    "changePercent": -0.88,
    "volume": "1.1M",
    "marketCap": "4.3T",
    "description": "Jewelry, watches & eyewear.",
    "sector": "Consumer Cyclical",
    "country": "India",
    "currency": "₹",
    "dayHigh": 4864.5,
    "dayLow": 4772,
    "prevClose": 4841
  },
  {
    "symbol": "MARUTI",
    "name": "Maruti Suzuki India",
    "price": 12103,
    "change": -235,
    "changePercent": -1.9,
    "volume": "659.8K",
    "marketCap": "3.8T",
    "description": "Passenger vehicle manufacturer.",
    "sector": "Consumer Cyclical",
    "country": "India",
    "currency": "₹",
    "dayHigh": 12458,
    "dayLow": 12103,
    "prevClose": 12338
  },
  {
    "symbol": "SUNPHARMA",
    "name": "Sun Pharma Ltd.",
    "price": 1837.3,
    "change": -30,
    "changePercent": -1.61,
    "volume": "2.9M",
    "marketCap": "4.4T",
    "description": "Specialty pharmaceuticals.",
    "sector": "Healthcare",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1877.2,
    "dayLow": 1837.3,
    "prevClose": 1867.3
  },
  {
    "symbol": "BAJFINANCE",
    "name": "Bajaj Finance Ltd.",
    "price": 1040.3,
    "change": 25.3,
    "changePercent": 2.49,
    "volume": "8.2M",
    "marketCap": "6.5T",
    "description": "Consumer finance & lending.",
    "sector": "Financial Services",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1040.3,
    "dayLow": 1019.1,
    "prevClose": 1015
  },
  {
    "symbol": "ADANIENT",
    "name": "Adani Enterprises Ltd.",
    "price": 3020,
    "change": 96.8,
    "changePercent": 3.31,
    "volume": "1.6M",
    "marketCap": "4.3T",
    "description": "Infrastructure incubator & energy.",
    "sector": "Industrials",
    "country": "India",
    "currency": "₹",
    "dayHigh": 3020,
    "dayLow": 2924.6,
    "prevClose": 2923.2
  },
  {
    "symbol": "WIPRO",
    "name": "Wipro Ltd.",
    "price": 166.83,
    "change": 0.43,
    "changePercent": 0.26,
    "volume": "23.6M",
    "marketCap": "1.7T",
    "description": "IT consulting & enterprise services.",
    "sector": "Technology",
    "country": "India",
    "currency": "₹",
    "dayHigh": 166.9,
    "dayLow": 163.3,
    "prevClose": 166.4
  },
  {
    "symbol": "HCLTECH",
    "name": "HCL Technologies",
    "price": 1249.3,
    "change": -9,
    "changePercent": -0.72,
    "volume": "2.9M",
    "marketCap": "3.4T",
    "description": "Engineering and R&D services.",
    "sector": "Technology",
    "country": "India",
    "currency": "₹",
    "dayHigh": 1260.8,
    "dayLow": 1235.6,
    "prevClose": 1258.3
  },
  {
    "symbol": "BAJAJ-AUTO",
    "name": "Bajaj Auto Ltd.",
    "price": 11414,
    "change": -86,
    "changePercent": -0.75,
    "volume": "296.8K",
    "marketCap": "3.1T",
    "description": "Two-wheeler and three-wheeler major.",
    "sector": "Consumer Cyclical",
    "country": "India",
    "currency": "₹",
    "dayHigh": 11540,
    "dayLow": 11406,
    "prevClose": 11500
  },
  {
    "symbol": "TATASTEEL",
    "name": "Tata Steel Ltd.",
    "price": 185.54,
    "change": -1.75,
    "changePercent": -0.93,
    "volume": "29.0M",
    "marketCap": "2.3T",
    "description": "Global steel producer.",
    "sector": "Materials",
    "country": "India",
    "currency": "₹",
    "dayHigh": 187.96,
    "dayLow": 185.54,
    "prevClose": 187.29
  },
  {
    "symbol": "ULTRACEMCO",
    "name": "UltraTech Cement",
    "price": 11014,
    "change": 250,
    "changePercent": 2.32,
    "volume": "458.8K",
    "marketCap": "3.2T",
    "description": "Grey cement and RMC leader.",
    "sector": "Materials",
    "country": "India",
    "currency": "₹",
    "dayHigh": 11060,
    "dayLow": 10819,
    "prevClose": 10764
  },
  {
    "symbol": "POWERGRID",
    "name": "Power Grid Corp.",
    "price": 270.3,
    "change": 6.55,
    "changePercent": 2.48,
    "volume": "17.9M",
    "marketCap": "2.5T",
    "description": "Inter-state power transmission.",
    "sector": "Utilities",
    "country": "India",
    "currency": "₹",
    "dayHigh": 270.3,
    "dayLow": 263.4,
    "prevClose": 263.75
  },
  {
    "symbol": "NTPC",
    "name": "NTPC Ltd.",
    "price": 323.65,
    "change": -5.95,
    "changePercent": -1.81,
    "volume": "9.4M",
    "marketCap": "3.1T",
    "description": "Thermal and renewable power.",
    "sector": "Utilities",
    "country": "India",
    "currency": "₹",
    "dayHigh": 330.85,
    "dayLow": 323.65,
    "prevClose": 329.6
  },
  {
    "symbol": "ONGC",
    "name": "ONGC Ltd.",
    "price": 232.8,
    "change": 0.37,
    "changePercent": 0.16,
    "volume": "11.1M",
    "marketCap": "2.9T",
    "description": "Crude oil & natural gas exploration.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 234.32,
    "dayLow": 231.75,
    "prevClose": 232.43
  },
  {
    "symbol": "BPCL",
    "name": "Bharat Petroleum",
    "price": 314,
    "change": 7,
    "changePercent": 2.28,
    "volume": "9.4M",
    "marketCap": "1.3T",
    "description": "Oil refining and fuel marketing.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 314.2,
    "dayLow": 308.25,
    "prevClose": 307
  },
  {
    "symbol": "IOC",
    "name": "Indian Oil Corp.",
    "price": 137,
    "change": 2.73,
    "changePercent": 2.03,
    "volume": "11.5M",
    "marketCap": "1.9T",
    "description": "National oil refiner & pipelines.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 137,
    "dayLow": 134.6,
    "prevClose": 134.27
  },
  {
    "symbol": "GAIL",
    "name": "GAIL (India) Ltd.",
    "price": 173.9,
    "change": 1.9,
    "changePercent": 1.1,
    "volume": "8.5M",
    "marketCap": "1.1T",
    "description": "Natural gas transmission & processing.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 174.65,
    "dayLow": 172,
    "prevClose": 172
  },
  {
    "symbol": "M&M",
    "name": "Mahindra & Mahindra",
    "price": 3052,
    "change": -24.5,
    "changePercent": -0.8,
    "volume": "3.0M",
    "marketCap": "3.7T",
    "description": "SUVs, commercial vehicles & tractors.",
    "sector": "Consumer Cyclical",
    "country": "India",
    "currency": "₹",
    "dayHigh": 3098.2,
    "dayLow": 3052,
    "prevClose": 3076.5
  },
  {
    "symbol": "COALINDIA",
    "name": "Coal India Ltd.",
    "price": 409.9,
    "change": -8.1,
    "changePercent": -1.94,
    "volume": "7.7M",
    "marketCap": "2.5T",
    "description": "Coal mining & energy resources.",
    "sector": "Energy",
    "country": "India",
    "currency": "₹",
    "dayHigh": 419.95,
    "dayLow": 409.65,
    "prevClose": 418
  },
  {
    "symbol": "TATAMOTORS",
    "name": "Tata Motors Ltd.",
    "price": 442.9,
    "change": 6.8,
    "changePercent": 1.56,
    "volume": "13.1M",
    "marketCap": "1.6T",
    "description": "Commercial & electric vehicles.",
    "sector": "Consumer Cyclical",
    "country": "India",
    "currency": "₹",
    "dayHigh": 445,
    "dayLow": 430.2,
    "prevClose": 436.1
  }
];
